### ISSUE TITLE
Know what's going to be installed before hand

### ISSUE THREAD

**Issue by tstavrianos** [halgari/wabbajack#19]
**Is your feature request related to a problem? Please describe.**
Since the modlist is embedded in the executable, there is no way to know what is ultimately included.

**Describe the solution you'd like**
Allow a review of what is going to be downloaded before you click begin (no option to alter, just view).

**Comment by halgari** [comment]
Yep, sounds great. I think what we can do here is generate a HTML overview of what's about to happen. We can list all the archives, their sources, and even the plugin/modlist. If we pull this HTML up in the system web browser (like we do for logging into the nexus), then users can save this file off, publish it, or whatever.
