### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by TheKinkouMaster** [halgari/wabbajack#36]
**Describe the bug**
I was going step by step with youtube tutorial. After authorising Wabbajack to use Nexus here is what Wabbajack logged:
- getting nexus api_key please click authorize if a browser window appears
- building a list of archives based on the files required
- at Alphaleonis.Win32.NativeError.ThrowException (... a lot of text followed by next and last log)
- (3) The system cannot find the path specified: [nexus_link_cache\mod-info-SkyrimSE-6194.json] - Can't continue.

And I'm stuck. I tried reinstalling game (as well as switching from Skyrim SE to regular Skyrim with all DLCs) and MO2 and redownloading Wabbajack but it still does not work and gets stuck at the same point
**Additional context**
Win 10, games: Skyrim SE and regular Skyrim with all DLCs. 
[Wabbajack.exe.log](https://github.com/halgari/wabbajack/files/3607055/Wabbajack.exe.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by Elscrux** [comment]
I got the same error but it's for every nexus mod I try to add. (Yes, I have nexus premium)
The MO2 meta file works fine but it's from GitHub.
![Annotation 2019-09-13 175317](https://user-images.githubusercontent.com/34755314/64876556-96aa1480-d64f-11e9-9b10-49f34497d972.png)

**Comment by TheKinkouMaster** [comment]
Worked. Thanks a lot
