### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by jaKz9** [halgari/wabbajack#39]
**Describe the bug**
The program won't start. Tried running it in and outside of the MO2 folder. Tried all compatibility settings. Tried restarting PC. I can see the process starting for 1 second on Task Manager's details tab alongside "WerFault.exe".

**Additional context**
Windows 10 1903 64bit

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by LostDragonist** [comment]
Are you using Rivatuner Statistics Server or some other overlay software?  Try disabling them.

**Comment by jaKz9** [comment]
That was it! Thank you very much.
