### ISSUE TITLE
Missing UIUtils.cs

### ISSUE THREAD

**Issue by erri120** [halgari/wabbajack#44]
The file `UIUtils.cs` got added at 4e95e78a69bdcc7c56a2ee7e77351dad4d0c3cb9 and included to `Wabbajack.csproj` [here](https://github.com/halgari/wabbajack/commit/4e95e78a69bdcc7c56a2ee7e77351dad4d0c3cb9#diff-a55ff5fb4b200ba0d9ebba4fbe27c5d5R184) but it's not available in the repo.

**Comment by halgari** [comment]
fixed, thanks
